import { Platform, StyleSheet } from "react-native";
export const COLORS = {
  ink: "#202124",
  cream: "#FFF8E8",
  paper: "#FFFDF8",
  muted: "#64615B",
  orange: "#F0523B",
  yellow: "#FFD541",
  sage: "#78DCAE",
  cobalt: "#2455DF",
  lavender: "#CBBAFF",
  pink: "#FF9BC2",
  line: "rgba(32,33,36,0.14)",
  lineStrong: "rgba(32,33,36,0.34)",
};

const shadow = Platform.select({
  ios: { shadowColor: COLORS.ink, shadowOffset: { width: 7, height: 8 }, shadowOpacity: 0.95, shadowRadius: 0 },
  android: { elevation: 7 },
  default: {},
});

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: COLORS.cream },
  flex: { flex: 1 },
  safe: { flex: 1, backgroundColor: COLORS.cream },
  loginScreen: { flex: 1, backgroundColor: COLORS.cream, overflow: "hidden" },
  mapDecor: { position: "absolute", width: 360, height: 300, right: -90, top: -45, transform: [{ rotate: "-14deg" }], opacity: 0.22 },
  mapLineH: { position: "absolute", height: 1, backgroundColor: COLORS.cobalt, width: 360 },
  mapLineV: { position: "absolute", width: 1, backgroundColor: COLORS.cobalt, height: 300 },
  loginTop: { flex: 1.15, paddingHorizontal: 24, paddingTop: 18, justifyContent: "space-between", paddingBottom: 24 },
  stamp: { alignSelf: "flex-end", backgroundColor: COLORS.yellow, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 7, paddingVertical: 8, paddingHorizontal: 14, transform: [{ rotate: "-2deg" }] },
  stampText: { color: COLORS.ink, fontWeight: "800", letterSpacing: 2, fontSize: 11 },
  wordmarkRow: { flexDirection: "row", alignItems: "center" },
  wordmarkDot: { width: 11, height: 11, borderRadius: 6, backgroundColor: COLORS.orange, marginRight: 7 },
  wordmarkDotCompact: { width: 7, height: 7, borderRadius: 4, marginRight: 5 },
  wordmark: { fontSize: 44, fontWeight: "900", letterSpacing: -2.5, color: COLORS.cobalt },
  wordmarkCompact: { fontSize: 28, letterSpacing: -1.3 },
  heroTitle: { fontSize: 36, lineHeight: 40, letterSpacing: -1.5, fontWeight: "900", color: COLORS.ink, marginTop: 24 },
  pageTitle: { fontSize: 48, lineHeight: 48, letterSpacing: -2.1, fontWeight: "900", color: COLORS.ink, marginTop: 14, marginBottom: 18 },
  bodyCopy: { fontSize: 17, lineHeight: 26, color: COLORS.muted, maxWidth: 340 },
  loginPanel: { backgroundColor: COLORS.paper, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, gap: 16, ...shadow },
  field: { gap: 8 },
  fieldLabel: { color: COLORS.muted, fontSize: 11, fontWeight: "800", letterSpacing: 1.7 },
  input: { minHeight: 54, borderWidth: 1, borderColor: COLORS.lineStrong, borderRadius: 12, paddingHorizontal: 16, fontSize: 16, color: COLORS.ink, backgroundColor: "#FFF9EC" },
  button: { minHeight: 56, borderRadius: 12, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 10, paddingHorizontal: 18 },
  buttonPrimary: { backgroundColor: COLORS.orange },
  buttonSecondary: { borderWidth: 1.5, borderColor: COLORS.lineStrong, backgroundColor: "transparent" },
  buttonQuiet: { backgroundColor: "transparent" },
  buttonPressed: { opacity: 0.82, transform: [{ translateY: 1 }] },
  buttonText: { color: "white", fontWeight: "800", fontSize: 16 },
  buttonQuietText: { color: COLORS.muted },
  finePrint: { fontSize: 11, color: COLORS.muted, textAlign: "center", lineHeight: 16 },
  backHeader: { minHeight: 78, paddingHorizontal: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: COLORS.line },
  circleButton: { width: 46, height: 46, borderRadius: 23, borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.paper, alignItems: "center", justifyContent: "center" },
  stepLabel: { color: COLORS.cobalt, fontSize: 10, fontWeight: "800", letterSpacing: 1.8 },
  screenBody: { padding: 24, paddingTop: 40, paddingBottom: 44, gap: 14 },
  eyebrow: { color: COLORS.cobalt, fontSize: 10, fontWeight: "900", letterSpacing: 2 },
  otpRow: { flexDirection: "row", gap: 10, marginVertical: 24 },
  otpInput: { flex: 1, height: 70, borderRadius: 12, borderWidth: 1, borderColor: COLORS.lineStrong, backgroundColor: COLORS.paper, textAlign: "center", fontSize: 30, color: COLORS.ink, fontWeight: "800" },
  noteRow: { flexDirection: "row", alignItems: "center", gap: 8, borderTopWidth: 1, borderTopColor: COLORS.line, paddingTop: 20, marginTop: 8 },
  liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: COLORS.sage },
  noteText: { color: COLORS.muted, fontSize: 12 },
  stickyHeader: { minHeight: 78, paddingHorizontal: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: COLORS.line },
  profileContent: { padding: 20, paddingBottom: 42 },
  sectionHeading: { paddingVertical: 24 },
  profileSection: { borderTopWidth: 1, borderTopColor: COLORS.line, paddingVertical: 24, gap: 14 },
  photoRow: { flexDirection: "row", alignItems: "center", gap: 18 },
  photoWrap: { width: 90, height: 90 },
  profilePhoto: { width: 90, height: 90, borderRadius: 45 },
  photoPlus: { position: "absolute", right: -2, bottom: -2, width: 30, height: 30, borderRadius: 15, backgroundColor: COLORS.orange, borderWidth: 3, borderColor: COLORS.cream, alignItems: "center", justifyContent: "center" },
  photoPlusText: { color: "white", fontSize: 20, fontWeight: "800", marginTop: -2 },
  sectionTitle: { fontSize: 16, fontWeight: "800", color: COLORS.ink },
  smallBody: { fontSize: 13, lineHeight: 19, color: COLORS.muted },
  textLink: { fontSize: 13, color: COLORS.cobalt, fontWeight: "800", marginTop: 4 },
  miniHeading: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  smallMuted: { color: COLORS.muted, fontSize: 12 },
  choice: { minHeight: 48, borderWidth: 1, borderColor: COLORS.line, borderRadius: 12, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 14, backgroundColor: COLORS.paper },
  choiceSelected: { borderColor: COLORS.orange, backgroundColor: "rgba(240,82,59,0.08)" },
  radio: { width: 14, height: 14, borderRadius: 7, borderWidth: 1, borderColor: COLORS.muted },
  radioSelected: { backgroundColor: COLORS.orange, borderColor: COLORS.cream, borderWidth: 4 },
  choiceText: { fontSize: 14, color: COLORS.ink },
  wrapRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { minHeight: 34, borderWidth: 1, borderColor: COLORS.lineStrong, borderRadius: 999, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "#FFF9EC" },
  chipSelected: { backgroundColor: COLORS.ink, borderColor: COLORS.ink },
  chipText: { color: COLORS.ink, fontSize: 12, fontWeight: "600" },
  chipTextSelected: { color: COLORS.cream },
  verifyCard: { flexDirection: "row", alignItems: "center", gap: 14, borderWidth: 1, borderColor: COLORS.line, borderRadius: 16, backgroundColor: COLORS.paper, padding: 18, marginVertical: 16 },
  verifyIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: COLORS.sage, alignItems: "center", justifyContent: "center" },
  verifiedBadge: { flexDirection: "row", alignItems: "center", gap: 5 },
  verifiedIconSmall: { width: 16, height: 16, borderRadius: 8, backgroundColor: COLORS.sage, alignItems: "center", justifyContent: "center" },
  verifiedText: { fontSize: 10, fontWeight: "800", color: COLORS.ink },
  discoverHeader: { minHeight: 84, paddingHorizontal: 20, paddingBottom: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  citySubtitle: { color: COLORS.muted, fontSize: 9, letterSpacing: 1.5, marginLeft: 12 },
  headerAvatar: { width: 46, height: 46, borderRadius: 23 },
  discoverContent: { paddingHorizontal: 16, paddingBottom: 30 },
  meetupBanner: { minHeight: 58, backgroundColor: COLORS.yellow, borderRadius: 10, flexDirection: "row", alignItems: "center", gap: 12, padding: 8 },
  ticketIcon: { width: 42, height: 42, borderRadius: 7, backgroundColor: COLORS.ink, alignItems: "center", justifyContent: "center" },
  ticketIconText: { color: COLORS.cream, fontSize: 22, fontWeight: "900" },
  bannerLabel: { fontSize: 9, fontWeight: "900", letterSpacing: 1.4, color: COLORS.ink },
  bannerTitle: { fontSize: 14, fontWeight: "800", color: COLORS.ink, marginTop: 2 },
  coordinateRow: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 3, paddingVertical: 14 },
  coordinateText: { fontSize: 8, color: "#8F7F71", letterSpacing: 0.6 },
  personCard: { backgroundColor: COLORS.paper, borderRadius: 18, borderWidth: 1, borderColor: COLORS.line, overflow: "hidden", ...shadow },
  personImageWrap: { height: 390, backgroundColor: "#eee" },
  personImage: { width: "100%", height: "100%" },
  residentRibbon: { position: "absolute", top: 14, left: 14, backgroundColor: COLORS.orange, paddingHorizontal: 11, paddingVertical: 8 },
  residentRibbonText: { color: "white", fontWeight: "900", fontSize: 9, letterSpacing: 1.4 },
  personDetails: { padding: 18 },
  personTitleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  personName: { fontSize: 38, letterSpacing: -1.6, fontWeight: "900", color: COLORS.ink },
  neighborhoodRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
  neighborhoodText: { fontSize: 12, color: COLORS.muted },
  detailBlock: { borderTopWidth: 1, borderTopColor: COLORS.line, marginTop: 15, paddingTop: 14 },
  detailLabel: { color: COLORS.cobalt, fontSize: 9, fontWeight: "900", letterSpacing: 1.5, marginBottom: 9 },
  detailGrid: { borderTopWidth: 1, borderTopColor: COLORS.line, flexDirection: "row", marginTop: 14, paddingTop: 13 },
  detailCol: { flex: 1 },
  detailColRight: { borderLeftWidth: 1, borderLeftColor: COLORS.line, paddingLeft: 12 },
  detailStrong: { color: COLORS.ink, fontSize: 12, lineHeight: 18, fontWeight: "600" },
  swipeActions: { flexDirection: "row", gap: 10, marginTop: 18 },
  matchContent: { padding: 20, paddingTop: 48, paddingBottom: 40, alignItems: "stretch" },
  matchTitle: { fontSize: 44, lineHeight: 44, fontWeight: "900", letterSpacing: -2, textAlign: "center", color: COLORS.ink, marginTop: 14, marginBottom: 26 },
  matchPeople: { flexDirection: "row", alignItems: "center", justifyContent: "center" },
  avatar: { width: 78, height: 78, borderRadius: 39, borderWidth: 3, borderColor: COLORS.orange },
  avatarYou: { borderColor: COLORS.yellow },
  matchConnector: { flexDirection: "row", alignItems: "center" },
  dash: { width: 22, borderTopWidth: 1, borderStyle: "dashed", borderColor: COLORS.muted },
  matchMark: { width: 30, height: 30, borderRadius: 15, backgroundColor: COLORS.ink, alignItems: "center", justifyContent: "center" },
  matchMarkText: { color: COLORS.cream, fontWeight: "900" },
  matchNames: { textAlign: "center", fontSize: 26, fontWeight: "900", color: COLORS.ink, marginTop: 16 },
  matchLocation: { textAlign: "center", color: COLORS.muted, fontSize: 13, marginBottom: 12 },
  revealLabel: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 24 },
  revealLine: { flex: 1, height: 1, backgroundColor: COLORS.lineStrong },
  revealText: { fontSize: 9, fontWeight: "900", letterSpacing: 1.6, color: COLORS.cobalt },
  mysteryCard: { backgroundColor: COLORS.yellow, borderRadius: 16, borderWidth: 2, borderColor: COLORS.ink, padding: 18, marginBottom: 18, ...shadow },
  mysteryTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  ticketNumber: { fontSize: 9, fontWeight: "800", letterSpacing: 1.4, color: COLORS.ink },
  seal: { width: 58, height: 58, borderRadius: 29, backgroundColor: COLORS.ink, alignItems: "center", justifyContent: "center", alignSelf: "center", marginVertical: 20 },
  spotCategory: { fontSize: 10, color: COLORS.ink, fontWeight: "900", letterSpacing: 1.4, marginTop: 8 },
  quote: { color: COLORS.ink, fontSize: 24, lineHeight: 30, fontWeight: "800", letterSpacing: -0.5, marginVertical: 18 },
  mysteryFooter: { borderTopWidth: 1, borderTopColor: COLORS.lineStrong, paddingTop: 12, flexDirection: "row", justifyContent: "space-between" },
  mysteryFooterText: { fontSize: 8, fontWeight: "800", color: COLORS.ink },
  messageOrbit: { height: 130, marginBottom: 14, position: "relative", justifyContent: "center", alignItems: "center" },
  orbitAvatar: { width: 58, height: 58, borderRadius: 29, position: "absolute", borderWidth: 3, borderColor: COLORS.orange },
  orbitCenter: { width: 58, height: 58, borderRadius: 29, backgroundColor: COLORS.cobalt, alignItems: "center", justifyContent: "center", borderWidth: 3, borderColor: COLORS.ink },
  orbitCenterText: { color: "white", fontSize: 26, fontWeight: "900" },
  agentCard: { backgroundColor: COLORS.paper, borderWidth: 1, borderColor: COLORS.line, borderRadius: 16, padding: 16, gap: 12, marginVertical: 10 },
  agentHeader: { flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingBottom: 12 },
  agentMark: { width: 38, height: 38, borderRadius: 19, backgroundColor: COLORS.cobalt, alignItems: "center", justifyContent: "center" },
  agentMarkText: { color: "white", fontWeight: "900", fontSize: 18 },
  agentTitle: { fontWeight: "800", color: COLORS.ink },
  agentSub: { color: COLORS.muted, fontSize: 11, marginTop: 2 },
  liveLabel: { color: COLORS.ink, backgroundColor: COLORS.sage, fontSize: 9, fontWeight: "900", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 999 },
  agentRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  agentRowText: { color: COLORS.ink, fontSize: 13 },
  feedbackCard: { backgroundColor: COLORS.paper, borderWidth: 1, borderColor: COLORS.line, borderRadius: 16, padding: 18, gap: 16, marginVertical: 10 },
  feedbackLabelRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  ratingRow: { flexDirection: "row", justifyContent: "space-between" },
  ratingDot: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: COLORS.lineStrong, alignItems: "center", justifyContent: "center" },
  ratingDotActive: { backgroundColor: COLORS.orange, borderColor: COLORS.orange },
  ratingNumber: { color: COLORS.ink, fontWeight: "800" },
  ratingNumberActive: { color: "white" },
  reactionLabel: { color: COLORS.cobalt, fontSize: 10, fontWeight: "900", letterSpacing: 1.5 },
  textarea: { minHeight: 120, borderWidth: 1, borderColor: COLORS.lineStrong, borderRadius: 12, padding: 14, textAlignVertical: "top", color: COLORS.ink, backgroundColor: "#FFF9EC", fontSize: 15 },
  thanksBody: { flex: 1, padding: 24, justifyContent: "center", gap: 18 },
  thanksStamp: { width: 72, height: 72, borderRadius: 36, backgroundColor: COLORS.sage, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: COLORS.ink },
  thanksTitle: { fontSize: 64, fontWeight: "900", letterSpacing: -3, color: COLORS.ink },
  thanksRule: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 16 },
});
